### ISSUE TITLE
ObjectDisposedException in SaeaLayerCallback.IoCompleted

### ISSUE THREAD

**Issue by lanwin** [Bobris/Nowin#49]
As have written in my last bug report, I have a load balancing app which disposed the server every 10 seconds, wait 10 seconds, starts it again and tests if our lib behaves correctly in a loop. While doing this I felt a few times over this exception which crashes the process.

```
Unhandled Exception: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.SocketAsyncEventArgs'.
   at System.Net.Sockets.SocketAsyncEventArgs.StartConfiguring()
   at System.Net.Sockets.SocketAsyncEventArgs.SetBufferInternal(Byte[] buffer, Int32 offset, Int32 count)
   at Nowin.SaeaLayerCallback.StartReceive(Byte[] buffer, Int32 offset, Int32 length)
   at Nowin.Transport2HttpHandler.RealStartNextReceive()
   at Nowin.Transport2HttpHandler.FinishReceive(Byte[] buffer, Int32 offset, Int32 length)
   at Nowin.SaeaLayerCallback.ProcessReceive()
   at Nowin.SaeaLayerCallback.IoCompleted(Object sender, SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

From what I could see with my limited knowledge of the codebase is that the ```_receiveEvent.SetBuffer(buffer, offset, length);``` lines should be moved into the try-catch block three lines below.

**Comment by Bobris** [comment]
Yes, it is true, will move it ...

**Comment by lanwin** [comment]
Seems to work fine now. Did 3,5 mio requests over night with my 10 seconds up and down and without any problem. Thx!
